dist: bionic
env:
    global: []
language: python
python:
    - "3.7"
before_install: []
install:
    - python -m pip install -U pip
    - pip install -U -r requirements.txt
script:
    - black --check .
